### ISSUE TITLE
SentryMiddleware problem with Django 1.10: TypeError: Initialization arguments are not supported

### ISSUE THREAD

**Issue by amiraliakbari** [getsentry/raven-python#886]
After updating from `5.27.1` to `5.28.0`, I get the error:

      File ".../wsgi.py", line 10, in <module>
        application = get_wsgi_application()
      File ".../venv/lib/python3.5/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
        return WSGIHandler()
      File ".../venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
        self.load_middleware()
      File ".../venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 84, in load_middleware
        mw_instance = middleware(handler)
      File ".../venv/lib/python3.5/site-packages/gevent/local.py", line 242, in __new__
        raise TypeError("Initialization arguments are not supported")
    TypeError: Initialization arguments are not supported

The error is raised in loading `raven.contrib.django.middleware.SentryMiddleware`. It seems related to the new change to fix Django 1.10 middleware warning.

Hopefully I'll check to provide a patch. I'm using `Django==1.10.2` using the older style `MIDDLEWARE = []` settings, if that is related.

**Comment by amiraliakbari** [comment]
As a site note, I'm used to not freezing my pip requirements, except for preventing major Django version change. Maybe this approach is risky for production, but I usually have no problem.

In fact, most of the times that upgrading to new (even minor) version caused serious problems, it was related to raven. Not many times, and I've even forgot when was the last time (probably around raven#4), but in general I expect more stability from a library that is used to report errors. Nonetheless raven/sentry are really great projects, thanks a lot. 👍

**Comment by lseelenbinder** [comment]
Have the exact same issue. Pegging raven version until this is fixed.

**Comment by mitsuhiko** [comment]
I'm sorry for the instability @amiraliakbari. There is so much stuff in the library at this point and so much surface and different versions it tries to cover :(

Going to look into this.

**Comment by mitsuhiko** [comment]
Wrong button

**Comment by mitsuhiko** [comment]
@lseelenbinder do you have a complete traceback of this?

**Comment by mitsuhiko** [comment]
Hi. I believe this was caused by an earlier commit that was pulled in. I pushed out 5.29.0 which I believe fixes this. My understanding is that this was isolated to uses of gevent with monkeypatching enabled.

**Comment by adamcharnock** [comment]
Sorry to say I'm still receiving this error (at version `5.30.0`). Downgrading to `5.27.0` fixes it. The stack trace is:

```
$ gunicorn habari.wsgi --log-file -
[2016-10-20 14:01:01 +0100] [85667] [INFO] Starting gunicorn 19.6.0
[2016-10-20 14:01:01 +0100] [85667] [INFO] Listening at: http://127.0.0.1:8000 (85667)
[2016-10-20 14:01:01 +0100] [85667] [INFO] Using worker: sync
[2016-10-20 14:01:01 +0100] [85670] [INFO] Booting worker with pid: 85670
[2016-10-20 13:01:01 +0000] [85670] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/adam/Envs/futurepump-habari/lib/python3.5/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/Users/adam/Envs/futurepump-habari/lib/python3.5/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/Users/adam/Envs/futurepump-habari/lib/python3.5/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/adam/Envs/futurepump-habari/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/adam/Envs/futurepump-habari/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/adam/Envs/futurepump-habari/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/adam/Envs/futurepump-habari/lib/python3.5/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/adam/Projects/futurepump-habari/habari/wsgi.py", line 17, in <module>
    application = get_wsgi_application()
  File "/Users/adam/Envs/futurepump-habari/lib/python3.5/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/Users/adam/Envs/futurepump-habari/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
    self.load_middleware()
  File "/Users/adam/Envs/futurepump-habari/lib/python3.5/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: Initialization arguments are not supported
[2016-10-20 13:01:01 +0000] [85670] [INFO] Worker exiting (pid: 85670)
[2016-10-20 14:01:01 +0100] [85667] [INFO] Shutting down: Master
[2016-10-20 14:01:01 +0100] [85667] [INFO] Reason: Worker failed to boot.
```

**Comment by mitsuhiko** [comment]
I pushed this out. I will try to figure out why this is not covered by tests now.
